#include <com/sun/star/uno/XInterface.idl>

module np { module com { module maharjansujit { module npDate {
        interface XnpDate {
          string dateToAD( [in] any date);
          string dateToBS( [in] any date);
          long BSMonth( [in] any date);
          string BSMonthString( [in] any date);
          string BSMonthNepali( [in] any date);
          string BSFinancialYear( [in] any date);
          string BSadd( [in] any date, [in] any day, [in] any month, [in] any year);
          string echo([in] string text);
          string greet();
        };
      };
    };
  };
};
