#include <com/sun/star/uno/XInterface.idl>

module np { module com { module maharjansujit { module npDate {
        interface XnpDate {
          string dateToAD( [in] any date);
          string dateToBS( [in] any date);
          string echo([in] string text);
          string greet();
        };
      };
    };
  };
};
